name: Release Please

on:
  # Automatically run on merge with main
  # push:
  #   branches:
  #     - main
  # Allows you to manually trigger this from the GitHub Actions tab:
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all tags so release-please can compare tags properly

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          release-type: "python"
          target-branch: "main"